# build version
version: '{build}'

# environment settings
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

platform: x64

# install required tools (java, maven)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

# Do not build on tags
skip_tags: true

# build and install artifacts
build_script:
  - mvn clean install -DskipTests

# verify artifacts
test_script:
  - mvn test
  - cd sofa-ark-samples
  - mvn clean install
  - cd sample-ark-plugin
  - mvn clean install
  - cd ../sample-springboot-ark
  - mvn test
  - cd ../..

# preserve dependencies between builds
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2